### ISSUE TITLE
ERROR: type GridLayout has no field needs_update

### ISSUE THREAD

**Issue by LouisHLAV** [JuliaGeometry/MeshViz.jl#13]
Hi,
I just stumbled upon this library while looking for mesh plotting tools and it looks amazing!

Unfortunately, I'm not able to run the simple grid example from the Meshes.jl docs...
Here is a minimal example of the error I'm getting:

```
julia> using Meshes, MeshViz

julia> import GLMakie

julia> grid = CartesianGrid(10, 10, 10)
10×10×10 CartesianGrid{3,Float64}
  minimum: Point(0.0, 0.0, 0.0)
  maximum: Point(10.0, 10.0, 10.0)
  spacing: (1.0, 1.0, 1.0)

julia> viz(grid, showfacets = true)
ERROR: type GridLayout has no field needs_update
Stacktrace:
  [1] getproperty(x::GridLayoutBase.GridLayout, f::Symbol)
    @ Base ./Base.jl:33
  [2] (::Makie.var"#926#927"{GridLayoutBase.GridLayout})(al::GridLayoutBase.Outside)
    @ Makie ~/.julia/packages/Makie/c5WJV/src/figures.jl:80
  [3] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [4] invokelatest
    @ ./essentials.jl:706 [inlined]
  [5] setindex!(observable::Observables.Observable{GridLayoutBase.Outside}, val::GridLayoutBase.Outside; notify::Observables.var"#9#11")
    @ Observables ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:207
  [6] setindex!
    @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:201 [inlined]
  [7] notify!
    @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:72 [inlined]
  [8] notify
    @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/AbstractPlotting.jl:35 [inlined]
  [9] Makie.Figure(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/c5WJV/src/figures.jl:82
 [10] Figure
    @ ~/.julia/packages/Makie/c5WJV/src/figures.jl:67 [inlined]
 [11] plot(P::Type{Makie.Combined{MeshViz.viz, ArgType} where ArgType}, args::CartesianGrid{3, Float64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:showfacets,), Tuple{Bool}}})
    @ Makie ~/.julia/packages/Makie/c5WJV/src/figureplotting.jl:18
 [12] viz(args::CartesianGrid{3, Float64}; attributes::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:showfacets,), Tuple{Bool}}})
    @ MeshViz ~/.julia/packages/Makie/c5WJV/src/recipes.jl:15
 [13] top-level scope
    @ REPL[6]:1
```

Julia version:
```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44* (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
```

Please let me know if I can provide any other useful information, or help in any way :)

**Comment by juliohm** [comment]
Hi @LouisHLAV , are you sure you are just using `import GLMakie`? If you try to `using GLMakie` you will get a bunch of functions names that may conflict with the Meshes.jl and MeshViz.jl packages. Also, can you please share the versions of the packages you are using? Try in a fresh environment.

**Comment by LouisHLAV** [comment]
Thanks for the fast response, @juliohm!
Yes, the reported output comes from a fresh environment (just using `import GLMakie`).
I also tried using `CairoMakie` in another session to no avail.

My package versions are as follow:
```
(@v1.6) pkg> status Meshes MeshViz GLMakie CairoMakie
      Status `~/.julia/environments/v1.6/Project.toml`
  [13f3f980] CairoMakie v0.5.10
  [e9467ef8] GLMakie v0.2.7
  [9ecf9c4f] MeshViz v0.1.9
  [eacbb407] Meshes v0.16.10
```

**Comment by juliohm** [comment]
Yes, I can confirm the issue and is probably not related to Meshes.jl nor MeshViz.jl but to Makie recipes. I will open an issue there.

**Comment by LouisHLAV** [comment]
Oh, I see... Thank you for looking into this @juliohm!

**Comment by juliohm** [comment]
The error was in the Makie side. I've bumped the version of Makie to v0.14 as a quick fix while they resolve the issue in version v0.13. You should be able to run the examples after the new version is merged in the registry: https://github.com/JuliaRegistries/General/pull/39877

**Comment by LouisHLAV** [comment]
Hi @juliohm, I could reproduce the fix on a clean environment, thanks!
But I couldn't get it working on my global env, even after updating (and later removing and readding the packages through `Pkg`).

Does Julia cache packages even after removal? Sorry if this is some kind of newbie mistake of mine.

Either way, this doesn't affect my workflow because I can build a new env, but I thought it was worth sharing.

**Comment by juliohm** [comment]
I think your other environment has packages that are downgrading Makie to
v0.13. Try to add ***@***.*** explicitly and see what happens.

Glad the fresh environment is working at least :)

**Comment by LouisHLAV** [comment]
That was it: Plotly was holding Makie back.
Now I can finally play with this gem! :D
