### ISSUE TITLE
Plotting meshes without viz

### ISSUE THREAD

**Issue by ga72kud** [JuliaGeometry/MeshViz.jl#28]
I would like to use the plot function (using Plots) for some meshes
```julia
points = Point2[(0,0), (1,0), (0,1), (1,1), (0.25,0.5), (0.75,0.5)]
    tris  = connect.([(1,5,3), (4,6,2)], Triangle)
    quads = connect.([(1,2,6,5), (4,3,5,6)], Quadrangle)
    mesh = SimpleMesh(points, [tris; quads])
    plot!(mesh, showfacets = true)
```
I want to adapt the visual appearance and changing the facet width for bigger dimensions. 
```julia
points = Point2[(300,-220), (440,-220), (300,-140), (440,-140), (330,-180), (360,-180)]
    tris  = connect.([(1,5,3), (4,6,2)], Triangle)
    quads = connect.([(1,2,6,5), (4,3,5,6)], Quadrangle)
    mesh = SimpleMesh(points, [tris; quads])
    plot!(mesh, showfacets = true, linewidth=5)
```

**Comment by juliohm** [comment]
@ga72kud `plot` is the default command in Makie to plot objects. `viz` is a recipe for Meshes.jl objects. You are probably confusing these two.

If you are using Meshes.jl already then it makes sense to use MeshViz.jl

**Comment by ga72kud** [comment]
Yes I know and I want to use both in one application.  I figured out it works. So I was wondering
