### ISSUE TITLE
Hi, how is viz! used?

### ISSUE THREAD

**Issue by berndmehnert** [JuliaGeometry/MeshViz.jl#29]
Hi, 
at first I want to say thank you for this project. I looked through your tests and noticed that there is no test where viz! is used. I guess viz! is used to draw multiple meshes within one window. Could you give an example for that? It seems that there is also no example in the documentation. 
Thank you for any answer ..

**Comment by juliohm** [comment]
Hi @berndmehnert , the version of `viz` with the exclamation mark works like any other Makie recipe:

```julia
viz(triangle) # start scene with triangle
viz!(quadrangle) # add quad to scene
viz!(circle) # add circle to scene
```

Please check Makie documentation to learn more.

**Comment by berndmehnert** [comment]
Thank you very much ;) I will look into Makie ..
