### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by ABbooy** [JuliaGeometry/MeshViz.jl#31]
Hi,

I am trying to install MeshViz inside VScode but I am getting the following error, 

>--------------------------------------------------------------------------------------------------------------------
(@v1.6) pkg> add MeshViz
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Meshes [eacbb407]:
 Meshes [eacbb407] log:
 ├─possible versions are: 0.1.0-0.23.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.23.1
 ├─restricted by compatibility requirements with MeshViz [9ecf9c4f] to versions: 0.15.0-0.23.1
 │ └─MeshViz [9ecf9c4f] log:
 │   ├─possible versions are: 0.1.0-0.5.0 or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.5.0
 │   └─restricted by compatibility requirements with CategoricalArrays [324d7699] to versions: 0.1.0-0.1.4 or uninstalled, leaving only versions: 0.1.0-0.1.4
 │     └─CategoricalArrays [324d7699] log:
 │       ├─possible versions are: 0.3.11-0.10.6 or uninstalled
 │       └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.3.11-0.8.3
 │         └─DataFrames [a93c6f00] log:
 │           ├─possible versions are: 0.11.7-1.3.4 or uninstalled
 │           ├─restricted to versions * by an explicit requirement, leaving only versions 0.11.7-1.3.4
 │           ├─restricted by compatibility requirements with RDatasets [ce6b1742] to versions: 0.13.0-1.3.4
 │           │ └─RDatasets [ce6b1742] log:
 │           │   ├─possible versions are: 0.5.0-0.7.7 or uninstalled
 │           │   └─restricted to versions * by an explicit requirement, leaving only versions 0.5.0-0.7.7
 │           └─restricted by compatibility requirements with OMJulia [0f4fe800] to versions: 0.11.7-0.21.8, leaving only versions: 0.13.0-0.21.8
 │             └─OMJulia [0f4fe800] log:
 │               ├─possible versions are: 0.1.0 or uninstalled
 │               └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 ├─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.1.0-0.22.2 or uninstalled, leaving only versions: 0.15.0-0.22.2
 │ └─SpecialFunctions [276daf66] log:
 │   ├─possible versions are: 0.7.0-2.1.7 or uninstalled
 │   ├─restricted by compatibility requirements with Knet [1902f260] to versions: 0.7.0-2.1.7
 │   │ └─Knet [1902f260] log:
 │   │   ├─possible versions are: 1.0.0-1.4.10 or uninstalled
 │   │   ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.4.10
 │   │   ├─restricted by compatibility requirements with CUDAdrv [c5f51814] to versions: [1.0.0-1.2.4, 1.3.3-1.4.10] or uninstalled, leaving only versions: [1.0.0-1.2.4, 1.3.3-1.4.10]
 │   │   │ └─CUDAdrv [c5f51814] log:
 │   │   │   ├─possible versions are: 0.8.0-6.3.0 or uninstalled
 │   │   │   └─restricted by julia compatibility requirements to versions: uninstalled
 │   │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: [1.0.0-1.3.6, 1.4.3-1.4.10] or uninstalled, leaving only versions: [1.0.0-1.2.4, 1.3.3-1.3.6, 1.4.3-1.4.10]
 │   │     └─CUDA [052768ef] log:
 │   │       ├─possible versions are: 0.1.0-3.12.0 or uninstalled
 │   │       ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-3.12.0] or uninstalled
 │   │       └─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.1.0-2.6.3 or uninstalled, leaving only versions: [2.3.0, 2.5.0-2.6.3] or uninstalled
 │   │         └─SpecialFunctions [276daf66] log: see above
 │   └─restricted by compatibility requirements with TensorFlow [1d978283] to versions: 0.7.0-0.10.3
 │     └─TensorFlow [1d978283] log:
 │       ├─possible versions are: 0.10.2-0.11.0 or uninstalled
 │       └─restricted to versions * by an explicit requirement, leaving only versions 0.10.2-0.11.0
 └─restricted by compatibility requirements with CategoricalArrays [324d7699] to versions: [0.1.0-0.10.1, 0.12.8-0.14.0] or uninstalled — no versions left
   └─CategoricalArrays [324d7699] log: see above
>------------------------------------------------------------------------------------------------------------------------

Any pointers will be helpful. 

Regards
Abhishek

**Comment by juliohm** [comment]
Try to install MeshViz.jl first in a clean environment and then try to
install the other packages you need afterwards. It is probably an
environment incompatibility issue.

Em ter., 16 de ago. de 2022 07:33, ABbooy ***@***.***>
escreveu:

**Comment by ABbooy** [comment]
Will do.

Thanks for the quick response.
