### ISSUE TITLE
possible to set colorbar limits for meshviz?

### ISSUE THREAD

**Issue by tanged123** [JuliaGeometry/MeshViz.jl#34]
currently, I have some code that visualizes a solved CFD mesh. I was wondering if it was possible to set a "color axis limit" in the meshviz to be consistent to the colorbar limits in makie. 

```
begin
fig = mke.Figure()
rangeval = [0,1]

#line to change below? 
#M = mach = range[0-0.7], want to convert to [0-1] for colors
ax,plotobj= viz(fig[1,1],turbine_mesh, colorscheme = :turbo, color = M)

cbar = mke.Colorbar(fig[1,2],label="Mach", width=25, limits = Float64.(rangeval),colormap = :turbo)
fig
```

**Comment by juliohm** [comment]
@tanged123 can you give an example of what you are trying to achieve? In theory all the recipes in MeshViz.jl are normal Makie recipes, so you should be able to compose visualizations with colorbars. Perhaps you are asking to forward some keyword argument that is currently not used in the final plot calls?

**Comment by juliohm** [comment]
Thank you for clarifying the issue. So the feature request consists of adding a new `clims` argument to the recipe and forward it to the underlying Makie call, correct? I am happy to review a PR.

**Comment by tanged123** [comment]
Yes a clims argument would be great.

**Comment by juliohm** [comment]
We now have a different function called `viewer` where we add other elements to the scene such as colorbars, etc. The function automatically picks color schemes, etc. Please try to use it instead and report a new issue if something is not ideal. :)

**Comment by ErickChacon** [comment]
Currently, what is the recommended way to plot static graphs with colorbars? I expected that something like the following would work:

```julia
import CairoMakie: CairoMakie, save, Figure, Axis
using Meshes, MeshViz

gd = meshdata(CartesianGrid(10,10), etable = (;id = rand(100)))
fig, ax, hm = viz(gd.geometry, color = gd.id)
CairoMakie.Colorbar(fig[1, 2], hm)
```

but it complaing because the `:colormap` key is not provided.

```julia
ERROR: KeyError: key :colormap not found
Stacktrace:
 [1] getindex(h::Dict{Symbol, Observables.Observable}, key::Symbol)
   @ Base ./dict.jl:498
 [2] getindex
   @ ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:91 [inlined]
 [3] getindex(x::MakieCore.Combined{MeshViz.viz, Tuple{CartesianGrid{2, Float64}}}, key::Symbol)
   @ MakieCore ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:187
 [4] getproperty
   @ ~/.julia/packages/MakieCore/6sckc/src/attributes.jl:78 [inlined]
 [5] Makie.Colorbar(fig_or_scene::GridLayoutBase.GridPosition, plot::MakieCore.Combined{MeshViz.viz, Tuple{CartesianGrid{2, Float64}}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/colorbar.jl:29
 [6] Makie.Colorbar(fig_or_scene::GridLayoutBase.GridPosition, plot::MakieCore.Combined{MeshViz.viz, Tuple{CartesianGrid{2, Float64}}})
   @ Makie ~/.julia/packages/Makie/Iqcri/src/makielayout/blocks/colorbar.jl:21
 [7] top-level scope
   @ REPL[303]:1
```

Setting up all the atributes of `Colorbar` work, but it does not feel right that we need to define `colormap` and `limits` on Colorbar.
```julia
gd = meshdata(CartesianGrid(10,10), etable = (;id = rand(100)))
fig, ax, hm = viz(gd.geometry, color = gd.id, colorscheme = viridis)
CairoMakie.Colorbar(fig[1, 2], colormap = :viridis, limits = extrema(df_grid.id))
```

**Comment by ErickChacon** [comment]
Also, It would be great if we can pass a colorscheme using `Reverse` something like `Reverse(:viridis)`.

**Comment by juliohm** [comment]
I think the viewer has the colorbar set, but I remember it was a limitation
of Makie.jl with recipes.

Regarding the reverse colorscheme, can you double check how it is done in
ColorSchemes.jl?

Em sáb., 6 de mai. de 2023 22:34, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment]
> I think the viewer has the colorbar set, but I remember it was a limitation of Makie.jl with recipes. Regarding the reverse colorscheme, can you double check how it is done in ColorSchemes.jl?

I can check both features. Both are useful for my use case.

**Comment by ErickChacon** [comment]
@juliohm I was experimenting with `MeshViz.jl` and how to setup a `Colorbar` for heatmaps using `Makie` code and I wanted to show that doing some few modifications we get a very flexible result where we can easily add a `Colorbar`, and get all the features of `heatmap` (set limits, transparency, color for values that are not inside the desired range, Reverse(:colormap), and so on):

```julia
@Makie.recipe(Viz, object) do scene
  Makie.Attributes(;
    Makie.default_theme(scene, Makie.Heatmap)...,
    size          = Makie.theme(scene, :markersize),
    color         = :slategray3,
    alpha         = 1.0,
    colorscheme   = nothing,
    facetcolor    = :gray30,
    showfacets    = false,
    decimation    = 0.0,
  )
end

function vizgrid2D!(plot)
  Makie.replace_automatic!(plot, :colorrange) do
    map(extrema, plot[:color])
  end

  grid        = plot[:object]
  color       = plot[:color]
  alpha       = plot[:alpha]
  colorscheme = plot[:colorscheme]

  attr = copy(Makie.Attributes(plot))

  cparams = Makie.@lift let
    nd = embeddim($grid)
    or = coordinates(minimum($grid))
    sp = spacing($grid)
    sz = size($grid)

    xs, ys = cartesiancenters(or, sp, sz, nd)

    C = reshape($color, sz)

    xs, ys, C
  end

  # unpack observable of parameters
  xs = Makie.@lift $cparams[1]
  ys = Makie.@lift $cparams[2]
  C  = Makie.@lift $cparams[3]

  Makie.heatmap!(plot, attr, xs, ys, C)
end
```

```julia

using Revise
import CairoMakie: CairoMakie as MK, save, Figure, Axis
using Meshes, MeshViz

gd = meshdata(CartesianGrid(10,10), etable = (;id = 1:100))

# colormap
fig = Figure()
ax = Axis(fig[1,1])
hm = viz!(ax, gd.geometry, color = gd.id, colormap = :RdBu,
    showfacets = true)
MK.Colorbar(fig[1, 2], hm)
```
![colormap](https://user-images.githubusercontent.com/7862458/236999839-0ba530db-716b-4eaa-b051-126cc4366e43.png)
```julia
# transparency
fig = Figure()
ax = Axis(fig[1,1])
hm = viz!(ax, gd.geometry, color = gd.id, colormap = (:RdBu, 0.5),
    showfacets = true)
MK.Colorbar(fig[1, 2], hm)
save("transparency.png", fig)
```
![transparency](https://user-images.githubusercontent.com/7862458/236999837-15aaa791-ddde-4bac-b4fb-1349a00de00e.png)
```julia
# limits
fig = Figure()
ax = Axis(fig[1,1])
hm = viz!(ax, gd.geometry, color = gd.id, colormap = (:RdBu, 0.5),
    showfacets = true, colorrange = (40,100), lowclip = :black)
MK.Colorbar(fig[1, 2], hm)
save("limits.png", fig)
```
![limits](https://user-images.githubusercontent.com/7862458/236999833-3d22ea2a-5b39-4956-bfde-49a93cd6ce15.png)
```julia
# reverse and transparency
fig = Figure()
ax = Axis(fig[1,1])
hm = viz!(ax, gd.geometry, color = gd.id, colormap = (MK.Reverse(:RdBu), 0.9),
    showfacets = true, colorrange = (40,100), lowclip = :black)
MK.Colorbar(fig[1, 2], hm)
save("reverse.png", fig)
```
![reverse](https://user-images.githubusercontent.com/7862458/236999829-26042505-aeb9-48bc-8db1-2d17283a4197.png)

Of course, this modification is probably causing problems for other graphic types because of ` Makie.default_theme(scene, Makie.Heatmap)...`, but maybe we can do a specific function for `CartessianGrids` to start with. Also, is there any reason you need to use `Colorant` and obtain the colors by ourselves? Will you be interested in a PR related to this issue, this is just a simple example?

**Comment by juliohm** [comment]
Thank you Erick for checking it. Can you see if it is possible to use our
preprocessing function for colors and combine it with the colorbar? Our
preprocessing function takes care of converting any Julia object to a color
and it would be nice to preserve that feature. Also we need a way that
works with any domain type, not just heat maps.

Em ter., 9 de mai. de 2023 06:13, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment]
@juliohm. Could you please explain why we need to preprocess the colors when `Makie` can do that?

**Comment by ErickChacon** [comment]
With respect to other graph types, I think I can generalize passing the main attributes that are important for `Colorbar` like `colorrange`, `colormap`, `lowclip`, `highclip`, and also some arguments that will be added to `Makie.jl`. For example there is a pull request to include `colorscale` to show the colorbar in `log` scale or any other desired transformations. If we procces the colors by ourselves, I think we miss all these features and probably new features.

**Comment by ErickChacon** [comment]
For specific plots we could use `convert_arguments`. For example for `CartesianGrid`, we know that we would like to plot a `heatmap`. Definining something like:

```julia
function MK.convert_arguments(::Type{<:MK.Heatmap}, grid::CartesianGrid, values)
  ....
  (xs, ys, C)
end
```
 would allow  us to call `heatmap` for `CartesianGrid` and use all existing features, would make really easy to add colorbars. I just tested it and works nice.

```julia
heatmap(grid, values, ...)
```

Sorry if I am making to much noise and it is out of the scope, but I am just throwing some ideas with the goal of having full compatibility with other `Makie` elements.

**Comment by juliohm** [comment]
Maybe they changed it recently based on what we did here I'm not sure. It
didn't work in the past.

Em ter., 9 de mai. de 2023 15:22, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment]
Just tested with other graph types, and it does not work for them.
