### ISSUE TITLE
wrong aspect ratio for 2D mesh

### ISSUE THREAD

**Issue by kylebeggs** [JuliaGeometry/MeshViz.jl#36]
When visualizing a 2D mesh, the plot comes out with the wrong aspect ratio.

1. How can you even correct this with the current version? I know with standard Makie you supply a `DataAspect()` to the axis, but I can't figure out how to do this with this recipe.
2. This should be the default anyways.

**Comment by juliohm** [comment]
Can you share an example?

The aspect is set like with any other Makie recipe:

```julia
fig, ax = viz(obj)
ax.aspect = DataAspect()
```

**Comment by kylebeggs** [comment]
Ok, thanks for answering 1, blunder on my part. But regarding 2, the below script does not give the correct aspect
```julia
using Meshes
using MeshViz
N = 50
θ = 0:(2π / N):(2π - 2π / (2 * N))
verts = Meshes.Point.(5 * cos.(θ), sin.(θ))
fan_con = [Meshes.connect((1, i, i + 1)) for i in 2:(N - 1)]
m = SimpleMesh(verts, fan_con)
fig, ax = viz(m)
```
![plot_2](https://user-images.githubusercontent.com/24981811/205135321-ee6272a8-28e3-43b5-b6a8-34cdb075711f.png)
 
and if you do `ax.aspect = DataAspect()` like you mentioned it does fix it.
![plot_fixed](https://user-images.githubusercontent.com/24981811/205135952-e436d70b-4cd3-4c13-9a27-b1ac1e50867e.png)

**Comment by juliohm** [comment]
Yes, I think we need to force the DataAspect in the call to the Makie built-in functions. Can you follow the recipe code and try to update the internal function call to Makie to force the aspect? It would be a nice improvement.

**Comment by kylebeggs** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/24981811/205410315-ca55c89c-816d-4d6e-87d7-c6b281f22d29.png">
 haha

**Comment by juliohm** [comment]
Oh yeah! I must have tried it in the past! Haha. Probably not possible
still?

Em sex., 2 de dez. de 2022 20:51, Kyle Beggs ***@***.***>
escreveu:

**Comment by kylebeggs** [comment]
I find it hard to believe its not possible, but I'm just getting started with Makie/MeshViz so I'm not the best person to try to figure this out. Its certainly not straightforward. Perhaps I make a post on slack or zulip (if they have one)

**Comment by juliohm** [comment]
You have to keep in mind that MeshViz.jl is nothing more and nothing less than Makie recipes. So if something like this is not working, it is not our fault. We are simply calling Makie internal functions to produce specific visualizations for our Meshes.jl types. Try to open an issue in Makie.jl itself if you would like to report that the aspect of the plot can't be changed within recipes.

**Comment by kylebeggs** [comment]
Yes I understand that, I made a post on the Makie slack and someone said they think it's still not possible so I shall open an issue on Makie.jl.

**Comment by juliohm** [comment]
Closing this issue as it is not related to the recipes we have here.
