### ISSUE TITLE
static graphs

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/MeshViz.jl#46]
Previously, when working with geotables, we were able to use something like

```julia
viz(geodata, variable = :elevation)
```
 which was veery handy and was easy to merge it with other plots using `Makie` syntax.  I know that now we have `viewer` which is useful for notebooks but I shouldn't we still keep the static version?

Edit: Of course, we can still get the geometries and set the color using one column, but is not handy. Also, users can also define their own function but usually users want a simple way to plot the data.

I think it would be great to have this previous function, allowing also incorporate the colorbar easily.

**Comment by juliohm** [comment]
viz(domain(gdata), color=gdata.var) is too cumbersome?

Em sáb., 6 de mai. de 2023 10:44, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment]
Not really. I just doesn't feel clean for an end-user. Anyway, if someone wants something more simple they can just wrap it in a function.

**Comment by juliohm** [comment]
Yes, I am under the impression that we can easily wrap that method to provide the previous syntax. If it becomes too annoying we can reintroduce the method for sure.
